-- =========================================================
-- Script de creación de la base de datos de prueba sobre gestión de venta de coches
-- Compatible con Oracle Database
-- Nota:
--   - Si ya existen las tablas y deseas recrearlas desde cero,
--     descomenta las líneas DROP TABLE que aparecen a continuación.
-- =========================================================

-- DROP TABLE VENTA;
-- DROP TABLE DISTRIBUCION;
-- DROP TABLE COCHE;
-- DROP TABLE MARCA;
-- DROP TABLE CLIENTE;
-- DROP TABLE CONCESIONARIO;

-- =========================================================
-- Creación de tablas
-- =========================================================

-- Table: CONCESIONARIO
CREATE TABLE CONCESIONARIO ( 
	cifc   SMALLINT,
	nombre VARCHAR2(25),
	ciudad VARCHAR2(50),
	cifmatriz SMALLINT,
	CONSTRAINT PK_concesionario PRIMARY KEY (cifc),
	CONSTRAINT FK1_concesionario FOREIGN KEY (cifmatriz) REFERENCES CONCESIONARIO (cifc) ON DELETE SET NULL
);

INSERT INTO CONCESIONARIO VALUES (1, 'SUR AUTO', 'SEVILLA', NULL);
INSERT INTO CONCESIONARIO VALUES (4, 'UNOAUTO', 'MADRID', NULL);
INSERT INTO CONCESIONARIO VALUES (2, 'MALAGA AUTO', 'MALAGA', 4);
INSERT INTO CONCESIONARIO VALUES (3, 'COSTA AUTO', 'HUELVA', 4);
INSERT INTO CONCESIONARIO VALUES (5, 'NORAUTO', 'SEVILLA', NULL);


-- Table: CLIENTE
CREATE TABLE CLIENTE (
	dni VARCHAR2(9),
	nombre VARCHAR2(50),
	apellidos VARCHAR2(50),
	ciudad VARCHAR2(50),
	CONSTRAINT PK_cliente PRIMARY KEY (dni)
);

INSERT INTO CLIENTE VALUES ('31345231E', 'JUAN', 'LOPEZ', 'SEVILLA');
INSERT INTO CLIENTE VALUES ('33245654T', 'ANA', 'SANCHEZ', 'HUELVA');
INSERT INTO CLIENTE VALUES ('21134589S', 'MANUEL', 'PEREZ', 'MALAGA');
INSERT INTO CLIENTE VALUES ('13567445E', 'ROSA', 'MAQUEDA', 'CADIZ');
INSERT INTO CLIENTE VALUES ('30345754N', 'PEDRO', 'GARCIA', 'JAEN');
INSERT INTO CLIENTE VALUES ('31224347D', 'JORGE', 'MESA', 'SEVILLA');
INSERT INTO CLIENTE VALUES ('39872396R', 'JUAN', 'GUTIERREZ', 'HUELVA');
INSERT INTO CLIENTE VALUES ('38884499Y', 'DAVID', 'ALBA', 'HUELVA');


-- Table: MARCA
CREATE TABLE MARCA (
	cifm SMALLINT,
	nombre VARCHAR2(10) NOT NULL,
	pais VARCHAR2(20) NOT NULL,
	CONSTRAINT PK_marca PRIMARY KEY (cifm)
);

INSERT INTO MARCA VALUES (1, 'SEAT', 'ESPAGNA');
INSERT INTO MARCA VALUES (2, 'WV', 'ALEMANIA');
INSERT INTO MARCA VALUES (3, 'FIAT', 'ITALIA');
INSERT INTO MARCA VALUES (4, 'FORD', 'USA');
INSERT INTO MARCA VALUES (5, 'RENAULT', 'FRANCIA');
INSERT INTO MARCA VALUES (6, 'BMW', 'ALEMANIA');


-- Table: COCHE
CREATE TABLE COCHE (
	codcoche SMALLINT,
	cifm SMALLINT NOT NULL,
	modelo VARCHAR2(10),
	matricula VARCHAR2(10),
	color VARCHAR2(15) DEFAULT 'BLANCO',
	CONSTRAINT PK_coche PRIMARY KEY (codcoche),
	CONSTRAINT FK1_coche FOREIGN KEY (cifm) REFERENCES MARCA (cifm) ON DELETE SET NULL
);

INSERT INTO COCHE VALUES (1, 1, 'MALAGA','CA3454Z','ROJO');
INSERT INTO COCHE VALUES (2, 1, 'IBIZA','3454DZD','BLANCO');
INSERT INTO COCHE VALUES (3, 2, 'GOLF','6565CTL','PLATA');
INSERT INTO COCHE VALUES (4, 2, 'POLO','3466BNN','BLANCO');
INSERT INTO COCHE VALUES (5, 3, 'STILO','8789DCD','PLATA');
INSERT INTO COCHE VALUES (6, 3, 'UNO','SE2672BM','CORINTO');
INSERT INTO COCHE VALUES (7, 4, 'FIESTA','CA2314D','BLANCO');
INSERT INTO COCHE VALUES (8, 4, 'MONDEO','6576BMB','VERDE');
INSERT INTO COCHE VALUES (9, 4, 'FOCUS','2233BMX','BURDEOS');
INSERT INTO COCHE VALUES (10, 1, 'LEON','5645CDZ','AMARILLO');



-- Table: DISTRIBUCION
CREATE TABLE DISTRIBUCION (
	cifc SMALLINT,
	codcoche SMALLINT,
	fecha DATE DEFAULT '01-01-2010' NOT NULL,
	CONSTRAINT PK_distribucion PRIMARY KEY (cifc,codcoche),
	CONSTRAINT FK1_distribuci�n FOREIGN KEY (cifc) REFERENCES CONCESIONARIO (cifc) ON DELETE SET NULL,
	CONSTRAINT FK2_distribuci�n FOREIGN KEY (codcoche) REFERENCES COCHE (codcoche) ON DELETE SET NULL
);

INSERT INTO DISTRIBUCION VALUES (1, 1, '10-11-2019');
INSERT INTO DISTRIBUCION VALUES (2, 1, '10-12-2019');
INSERT INTO DISTRIBUCION VALUES (1, 2, '18-07-2023');
INSERT INTO DISTRIBUCION VALUES (1, 3, '06-01-2021');
INSERT INTO DISTRIBUCION VALUES (1, 4, '31-12-2021');
INSERT INTO DISTRIBUCION VALUES (2, 4, '10-03-2022');
INSERT INTO DISTRIBUCION VALUES (2, 5, '24-06-2017');
INSERT INTO DISTRIBUCION VALUES (3, 6, '08-05-2019');
INSERT INTO DISTRIBUCION VALUES (3, 7, '12-10-2023');
INSERT INTO DISTRIBUCION VALUES (3, 8, '19-02-2018');
INSERT INTO DISTRIBUCION VALUES (4, 9, '21-08-2015');
INSERT INTO DISTRIBUCION VALUES (4, 2, '18-02-2016');
INSERT INTO DISTRIBUCION VALUES (4, 5, '09-05-2017');



-- Table: VENTA
CREATE TABLE VENTA (
	cifc SMALLINT,
	codcoche SMALLINT,
	dni VARCHAR2(9),
	fechaventa	DATE NOT NULL,
	pvp	NUMBER(12,2) DEFAULT 0,
	CONSTRAINT PK_venta PRIMARY KEY (cifc,codcoche,dni),
	CONSTRAINT FK1_venta FOREIGN KEY (cifc) REFERENCES CONCESIONARIO (cifc) ON DELETE SET NULL,
	CONSTRAINT FK2_venta FOREIGN KEY (codcoche) REFERENCES COCHE (codcoche) ON DELETE SET NULL,
	CONSTRAINT FK3_venta FOREIGN KEY (dni) REFERENCES CLIENTE (dni) ON DELETE SET NULL
);

INSERT INTO VENTA VALUES (2, 1, '21134589S', '16-12-2019', 7565);
INSERT INTO VENTA VALUES (1, 3, '21134589S', '16-05-2021', 18567);
INSERT INTO VENTA VALUES (2, 4, '13567445E', '04-07-2022', 9450);
INSERT INTO VENTA VALUES (3, 6, '38884499Y', '04-07-2019', 6950);
INSERT INTO VENTA VALUES (3, 7, '38884499Y', '12-11-2016', 7123);
INSERT INTO VENTA VALUES (3, 8, '31224347D', '23-03-2018', 19567);
INSERT INTO VENTA VALUES (4, 2, '31345231E', '25-03-2021', 7234);
INSERT INTO VENTA VALUES (4, 5, '13567445E', '21-06-2017', 16750);

